//
//  Printer.swift
//  SwiftGodot
//
//  Created by Elijah Semyonov on 16/10/2024.
//

import Foundation

public class Printer {
    public let name: String
    // Where we accumulate our output for the p/b routines
    public var result = ""
    public var indentStr = ""          // The current indentation string, based on `indent`
    public var indent = 0 {
        didSet {
            indentStr = String (repeating: "    ", count: indent)
        }
    }
    
    let defaultSuffix: String
    
    public init(name: String) {
        self.name = name
        self.defaultSuffix = "\n"
    }

    public func preamble () {
        p ("// This file is autogenerated, do not edit\n")
        p ("@_implementationOnly import GDExtension\n")
        p("""
        // This file is autogenerated, do not edit
        @_implementationOnly import GDExtension
        
        #if CUSTOM_BUILTIN_IMPLEMENTATIONS
        import Foundation
        #endif
        """)

    }
    
    // Prints the string, indenting any newlines with the current indentation
    public func p (_ str: String) {
        for x in str.split(separator: "\n", omittingEmptySubsequences: false) {
            print ("\(indentStr)\(x)", to: &result)
        }
    }
    
    public func `if`(_ `if`: String, then: () -> Void, else: () -> Void) {
        p("if \(`if`) {")
        indent += 1
        then()
        indent -= 1
        p("} else {")
        indent += 1
        `else`()
        indent -= 1
        p("}")
    }
    
    // Prints a variable definition
    public func staticVar (visibility: String = "", name: String, type: String, block: () -> ()) {
        b ("\(visibility)static let \(name): \(type) =", suffix: "()\n", block: block)
    }

    // Prints a block, automatically indents the code in the closure
    public func b (_ str: String, arg: String? = nil, suffix: String = "\n", block: () -> ()) {
        p (str + " {" + (arg ?? ""))
        indent += 1
        let saved = indent
        block ()
        if indent != saved {
            print ("Indentation out of sync, the nested block messed with indentation")
        }
        indent -= 1
        p ("}\(suffix)")
    }

    public func callAsFunction(_ str: String) {
        p (str)
    }
    
    public func callAsFunction(_ str: String, arg: String? = nil, suffix: String = "\n", block: () -> ()) {
        b (str, arg: arg, suffix: suffix, block: block)
    }
}
